spring:

  mvc:
    servlet:
      path: /api/accounts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
#    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: postgres
#    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      enabled: true

server:
  port: 8081

auth:
  token:
    private-key-path: keys/private_key.pem
    public-key-path: keys/public_key.pem
    access-expire-min: 15
    refresh-expire-days: 30

images:
  storage-path: /app/uploads/avatars
  default-avatar-path: /static/images/default-avatar.jpeg
