services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: volga
        networks:
            - work

    pgadmin:
        image: dpage/pgadmin4
        container_name: pga
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - postgres
        networks:
            - work

    rabbitmq:
        image: "rabbitmq:4"
        container_name: rabbitmq
        ports:
            - "5672:5672"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - work

#    python-example:
#        build:
#            context: ./backend/example/
#        container_name: example_service
#        ports:
#            - "8081:8081"
#        depends_on:
#            - rabbitmq
#            - postgres
#            - redis
#        env_file:
#            - ./backend/example/.env
#        networks:
#            - work

networks:
    work:

volumes:
    postgres_data:
    redis_data:
    elastic_data: