"""all_tables

Revision ID: 4c338d64feb5
Revises: 
Create Date: 2025-02-25 21:56:51.855416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4c338d64feb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('type',
                              sa.Enum('PEDESTRIAN', 'CAR', 'ORIENTEERING', 'ALPINISM', 'CYCLING', 'CAMPING', 'SKIING',
                                      'KAYAKING', 'SUP_SURFING', 'DIVING', 'RAFTING', 'HORSEBACK_RIDING', 'SNOWMOBILE',
                                      'BUGGY', 'ENDURO', 'OFF_ROAD', 'TRAIN', name='routetype'), nullable=False),
                    sa.Column('media', sa.String(), nullable=False),
                    sa.Column('is_public', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
