"""add distance

Revision ID: 53cd9ca9d5d9
Revises: d18fad59a28a
Create Date: 2025-02-27 15:17:44.050102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cd9ca9d5d9'
down_revision: Union[str, None] = 'd18fad59a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('distance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'distance')
    # ### end Alembic commands ###
