"""add comments

Revision ID: 443f67945e07
Revises: 1777dd2e8f68
Create Date: 2025-02-26 09:38:26.304409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443f67945e07'
down_revision: Union[str, None] = '1777dd2e8f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('owner_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'owner_id')
    # ### end Alembic commands ###
