"""edit

Revision ID: 0da8676632ea
Revises: 88b21d3ac853
Create Date: 2025-02-26 11:19:04.988776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da8676632ea'
down_revision: Union[str, None] = '88b21d3ac853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('route_photos_route_id_fkey', 'route_photos', type_='foreignkey')
    op.create_foreign_key(None, 'route_photos', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.drop_column('routes', 'media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'route_photos', type_='foreignkey')
    op.create_foreign_key('route_photos_route_id_fkey', 'route_photos', 'points', ['route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
