"""edit photo

Revision ID: 88b21d3ac853
Revises: 78f3761affaa
Create Date: 2025-02-26 10:30:46.298375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '88b21d3ac853'
down_revision: Union[str, None] = '78f3761affaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('route_id', sa.UUID(), nullable=False))
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'post_id')
    op.add_column('points', sa.Column('photo', sa.String(), nullable=False))
    op.drop_column('points', 'photo_path')
    op.add_column('route_photos', sa.Column('photo_path', sa.String(), nullable=False))
    op.drop_column('route_photos', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_photos', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('route_photos', 'photo_path')
    op.add_column('points', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('points', 'photo')
    op.add_column('comments', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'routes', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'route_id')
    # ### end Alembic commands ###
