"""add status

Revision ID: cea5436af167
Revises: 4c338d64feb5
Create Date: 2025-02-25 22:26:44.267416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea5436af167'
down_revision: Union[str, None] = '4c338d64feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

route_status_enum = sa.Enum('APPROVED', 'REJECTED', 'MODERATION', name='routestatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    route_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('routes', sa.Column('status', route_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'status')
    route_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
