"""edit reset model

Revision ID: b6be473a6a70
Revises: 53ae3b73c6b2
Create Date: 2024-12-06 16:15:32.520331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6be473a6a70'
down_revision: Union[str, None] = '53ae3b73c6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_session', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'reset_session', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reset_session', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_session', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reset_session', type_='foreignkey')
    op.drop_column('reset_session', 'user_id')
    # ### end Alembic commands ###
