"""+district

Revision ID: e9e14003f543
Revises: 71ca0ab76d0a
Create Date: 2024-12-07 14:20:12.830392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e9e14003f543'
down_revision: Union[str, None] = '71ca0ab76d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('district_id', sa.UUID(), nullable=True))
    op.drop_column('users', 'district')
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'patronymic')
    op.drop_table('districts')
    # ### end Alembic commands ###
