"""edit user

Revision ID: 71ca0ab76d0a
Revises: 4aa261fb5e25
Create Date: 2024-12-07 14:05:13.033299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ca0ab76d0a'
down_revision: Union[str, None] = '4aa261fb5e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'district')
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
