"""edit all-tables

Revision ID: 3dd83612108f
Revises: ebf6fb807a18
Create Date: 2025-02-25 18:59:59.002342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd83612108f'
down_revision: Union[str, None] = 'ebf6fb807a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('districts')
    op.drop_constraint('users_district_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'number')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'region')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_man')
    op.drop_column('users', 'patronymic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_man', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('district_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('number', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_district_id_fkey', 'users', 'districts', ['district_id'], ['id'], ondelete='CASCADE')
    op.create_table('districts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='districts_pkey')
    )
    # ### end Alembic commands ###
